// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwEoax0RzfSADgwVB8o9aVjZ38hTHFIY',
    appId: '1:183589953082:web:e2c35c3f15c148376d1f03',
    messagingSenderId: '183589953082',
    projectId: 'cit-club',
    authDomain: 'cit-club.firebaseapp.com',
    storageBucket: 'cit-club.appspot.com',
    measurementId: 'G-QLYK9CNSXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPOfdN8_mux7NC8oAW703GUrDrrMkoa4c',
    appId: '1:183589953082:android:f10c7e38d64a07066d1f03',
    messagingSenderId: '183589953082',
    projectId: 'cit-club',
    storageBucket: 'cit-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8l5ry7gHlNE2SeSDnrnrA3rXOvnFfZQg',
    appId: '1:183589953082:ios:5b63a8435edd678c6d1f03',
    messagingSenderId: '183589953082',
    projectId: 'cit-club',
    storageBucket: 'cit-club.appspot.com',
    iosClientId: '183589953082-omqgh5jq6dr1akgc7td2dobieosroljg.apps.googleusercontent.com',
    iosBundleId: 'com.example.citClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8l5ry7gHlNE2SeSDnrnrA3rXOvnFfZQg',
    appId: '1:183589953082:ios:5b63a8435edd678c6d1f03',
    messagingSenderId: '183589953082',
    projectId: 'cit-club',
    storageBucket: 'cit-club.appspot.com',
    iosClientId: '183589953082-omqgh5jq6dr1akgc7td2dobieosroljg.apps.googleusercontent.com',
    iosBundleId: 'com.example.citClub',
  );
}
